server:
  port: 3334
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
spring:
  application:
    name: service-feign
#开启Feign熔断能力
feign:
  hystrix:
    enabled: true